export const stutiData = [
  {
    id: 1,
    title: "Hanuman Chalisa",
    category: "Stuti",
    subCategory: "Hanuman Stuti",
    image: "/hanumanchalisa.jpeg",
  },
  {
    id: 2,
    title: "Sankat Mochan",
    category: "Stuti",
    subCategory: "Sankat Mochan Stuti",
    image: "/sankatmochan.jpg",
  },
  {
    id: 3,
    title: "Bajrang Baan",
    category: "Stuti",
    subCategory: "Hanuman Stuti",
    image: "/shri-bajrang-baan.webp",
  },
  {
    id: 7,
    title: "Namami Bhakta Vatsalam",
    category: "Stuti",
    subCategory: "Ram Stuti",
    image: "/namamibhaktabhatsalam.jfif",
  },
  {
    id: 8,
    title: "Vaye prakat Kripala",
    category: "Stuti",
    subCategory: "Prat Kal Ram Stuti",
    image: "/vayeprakatkiprala.jfif",
  },
  {
    id: 10,
    title: "Vog Aarati",
    category: "Aarati",
    subCategory: "Vog Aarati",
    image: "/VogAarati.png",
  },
  {
    id: 9,
    title: "Jay Ram rupa",
    category: "Stuti",
    subCategory: "Ram Stuti",
    image: "/Jaya_ram_rup.jfif",
  },
  {
    id: 12,
    title:"Bandey Bidenatanaya",
    category: "Stuti",
    subCategory: "Prat kal Stuti",
    image: "/Bandey_bidenataya.png",
    
  },
  {
    id: 4,
    title: "Namamishamisham",
    category: "Stuti",
    subCategory: "Shiva Stuti",
    image: "/namamishamishan.JPG",
  },
  {
    id: 5,
    title: "Gurupadukavyam",
    category: "Stuti",
    subCategory: "Guru paduka Stuti",
    image: "/gurupadukavyam.jfif",
  },
  {
    id: 6,
    title: "Swastivachanam",
    category: "Stuti",
    subCategory: "Swastivachanam Stuti",
    image: "/swastibachan.jfif",
  },
  {
    id: 11,
    title: "Jaykar",
    category: "Aarati",
    subCategory: "Jaykar Aarati",
    image: "/Jaykar.png",
  }
];
